### ISSUE TITLE
error: pathspec 'master' did not match any file(s) known to git.

### ISSUE THREAD

**Issue by muzir** [lemiorhan/git-kata#2]
After "switch_user edison" function when "switch_branch master" running below errors are logged to console.

```
fatal: Not a valid object name: 'master'.
New master branch created
error: pathspec 'master' did not match any file(s) known to git.
```

**Comment by lemiorhan** [comment]
Yeah you are right. When you switch to edison user, since there exists no commits yet, master branch cannot be found when we intent to switch to master branch. 

I deleted the `stich_branch master` command after switching user edison. Thanks a lot for leting us know.
